### ISSUE TITLE
Copy selection instead of whole document

### ISSUE THREAD

**Issue by mvdkwast** [mvdkwast/obsidian-copy-as-html#18]
### Discussed in https://github.com/mvdkwast/obsidian-copy-as-html/discussions/17

<div type='discussions-op-text'>

<sup>Originally posted by **aravindk100** January 12, 2023</sup>
Copy selection as HTML – There is another plugin that does similar capability, but that plugin does not appear to be actively developed  and has a few bugs that limit the usage of it. With all the capability, this plugin as this would be an wonderful addition.

</div>

**Comment by vialcollet** [comment]
I fully agree this would be absolutely fantastic!
And thanks for the work so far.

**Comment by RaffaeleBianc0** [comment]
+1 on this request!
And also thanks for this plugin, so fundamental in my daily usage of Obsidian!

**Comment by mvdkwast** [comment]
Released in v5.0.0. Thanks @Brradut !

**Comment by aravindk100** [comment]
Just tested it and this works very well. Well implemented especially with the smart choice between selection or full document. Thank you.
