### ISSUE TITLE
Strip off links to obsidian documents

### ISSUE THREAD

**Issue by mvdkwast** [mvdkwast/obsidian-copy-as-html#19]
### Discussed in https://github.com/mvdkwast/obsidian-copy-as-html/discussions/17

<div type='discussions-op-text'>

<sup>Originally posted by **aravindk100** January 12, 2023</sup>
Can you add an option to strip off links and convert them to plain text - Links are for other notes, which does not mean much when I copy and paste into another software like Outlook? 
</div>

**Comment by karlla1220** [comment]
Similiar issue are also on footnotes.

**Comment by mvdkwast** [comment]
Thanks for reporting @karlla1220, I moved this to a new issue for this. Feel free to complete there how you think that footnotes should be handled.

**Comment by aravindk100** [comment]
Thanks for implementing this, did not even realize this was implemented until now.
