### ISSUE TITLE
Footnotes are not handled correctly

### ISSUE THREAD

**Issue by mvdkwast** [mvdkwast/obsidian-copy-as-html#20]
Similiar issue are also on footnotes.

_Originally posted by @karlla1220 in https://github.com/mvdkwast/obsidian-copy-as-html/issues/19#issuecomment-1410472037_

**Comment by mvdkwast** [comment]
What would be the best way to address this ?

- just remove the link element, but continue to display the `[1]`, and the foot-notes
- hide the link and foot-notes entirely
- insert the foot-note in a title element so it can be displayed on hover, depending on the editor, and dropping styling elements along the way.
- something else

**Comment by mvdkwast** [comment]
Fixed in release 0.4.0

**Comment by mvdkwast** [comment]
Hi @toddmedema,

I cannot reproduce this with Obsidian 1.4.16 and this plugin version 0.6.0. 

How footnotes are displayed is controlled by the footnote setting :

![image](https://github.com/mvdkwast/obsidian-copy-as-html/assets/2441349/201400c3-7e89-466a-ae4b-fc21ca9632f7)

This is how it renders in Google Docs : 

![image](https://github.com/mvdkwast/obsidian-copy-as-html/assets/2441349/0d0e7043-01e8-472a-bc36-a79d6d0d56bd)

**Comment by mvdkwast** [comment]
Just a thought, @toddmedema, maybe you forgot the colon (:) in the foot-note ?

The following document renders as `My foot-note reference1` in both reading mode and when copied because a column is missing after `[^1]`

```
My foot-note reference[^1] 

[^1 ] my foot-note
```

**Comment by toddmedema** [comment]
Thanks for taking a look! :)
