### ISSUE TITLE
Copy as HTML button by right clicking doesn't seem to be working?

### ISSUE THREAD

**Issue by weldcloudnotes** [mvdkwast/obsidian-copy-as-html#31]
When I click on the button to Copy to HTML nothing seems to happen

<img width="514" alt="image" src="https://github.com/mvdkwast/obsidian-copy-as-html/assets/35844430/6466cae6-8d25-4ca2-9546-fe88646b992c">

But when I try to do it with my hotkey'd command, there is a short progress bar and I do get the document into the clipboard, so when I use the hotkey it works just fine

<img width="478" alt="image" src="https://github.com/mvdkwast/obsidian-copy-as-html/assets/35844430/29c5ca8d-136a-4ad9-9aff-394e0a9a161c">

The plugin is working great for me with the hotkey, but in general I don't use hotkeys for tasks like these (that I don't do that often). I wonder if this is a bug or if there's any plugin that this is incompatible with?

Edit: further information on this:

It seems that I can only copy a document to HTML when my text cursor is enabled in a file
<img width="288" alt="image" src="https://github.com/mvdkwast/obsidian-copy-as-html/assets/35844430/1b9032a7-ca4f-4405-b9bc-7d728d49392c">

If I select something from the vault (left click) obsidian will automatically place the cursor at the beginning of the file and like this I can use Copy as HTML through the hotkey shortcut.

If I right click any file on the vault, the cursor will be removed and I no longer can copy to html (I can't copy even when I use the hotkey in this scenario)

**Comment by mvdkwast** [comment]
Welcome @weldcloudnotes, and thanks for reporting ! The action is indeed applied to the active editor view, so it doesn't work when no editor windows is in focus. 

Marking this as "enhancement", not sure when I will have time to look into this.
