### ISSUE TITLE
Copy note with embedded heading of another note

### ISSUE THREAD

**Issue by 64er** [mvdkwast/obsidian-copy-as-html#32]
I often have a heading of one note embedded in another note. For example:

note a:
-------
<MANY OTHER TEXT OF NOTE A>

## Heading XYZ
Some Text under this heading

## Heading ABC
<MANY OTHER TEXT OF NOTE A

note b:
-------
![[note a#Heading XYZ]]

In Preview of note b I only see from note a:
## Heading XYZ
Some Text under heading

Wehn I export it with your plugin. In the html output of note b I see all content of note a and not only the heading XYZ

**Comment by mvdkwast** [comment]
Hi @64er, thanks for your report and the detailed example. Handling transclusions properly is a bit finnicky. Marking this as a bug, not sure when I will have time to fix this :/

**Comment by mvdkwast** [comment]
This seems to have been fixed in Obsidian (the new renderer handles transclusions correctly now)
