### ISSUE TITLE
Recognizing an Alias

### ISSUE THREAD

**Issue by eb2ai** [mvdkwast/obsidian-copy-as-html#39]
Currently, this will remove the wikilink brackets, which is excellent, but it would be even better if there were an option to parse everything out but the alias.

For instance the wikilink of `[[Flintstone, Fredrick|Fred]]`

Currently pastes as `Flintstone, Fredrick|Fred`

Ideally, we would have an option for it to paste as `Fred`

**Comment by mvdkwast** [comment]
Thanks for reporting this, and I fully agree. I probably won't have the opportunity to look into this before september, but I might be able to merge a pull request.

**Comment by mvdkwast** [comment]
I cannot reproduce this with Obsidian 1.4.11 : 

```markdown
[[Flintstone, Fredrick|Fred]]
```

renders to 
```html
<span class="internal-link">Fred</span>
```

Feel free to reopen if you can still reproduce it !
