### ISSUE TITLE
Nothing copied on iOS

### ISSUE THREAD

**Issue by lebigot** [mvdkwast/obsidian-copy-as-html#41]
**Describe the bug**

On iOS, the Copy as HTML command doesn't touch the clipboard, so nothing is copied.

**To Reproduce**
1. Use Obsidian for iOS (version 1.3.5, for instance).
2. Select text.
3. In the tools ribbon (below the document, typically above the keyboard), select the Command Palette (">_" icon).
4. Select the "Copy as HTML" command.

The result is that the clipboard is left *untouched*.

**Expected behavior**

Instead, an HTML version of the text should go to the clipboard.

**Smartphone:**
 - Device: iPhone 13 Pro
 - OS: 16.5.1
 - Browser: Safari
 - Version: ? (version in iOS 16.5.1), with *default* Experimental features.

This is really handicapping, when HTML (and not Markdown) is important (for example for pasting into an email).

**Comment by mvdkwast** [comment]
Hi @lebigot, unfortunately there is no mobile support yet. I wonder how you got this to install on your iPhone, since this plugin is marked as desktop only in the manifest.

**Comment by lebigot** [comment]
OK, thanks for clarifying this.

The plugin was installed on my phone through a cloud sync.

For what it's worth, a (cumbersome and imperfect) workaround is to copy the Markdown as usual and to paste it into a Markdown app that accepts raw Markdown (Type, for example).
