### ISSUE TITLE
Images in Transcluded Notes are missing

### ISSUE THREAD

**Issue by senorvalenz** [mvdkwast/obsidian-copy-as-html#43]
**Describe the bug**

**To Reproduce**
1. Transclude a note (containing at least one image) into another "Parent Note"
2. Copy the Parent Note to HTML, then paste into empty Google Docs document

**Expected behavior**
Images from the transcluded note will be visible.  Actual behavior, images appear as Obsidian path text placeholders

**Screenshots**
*Obsidian Source Mode*
![image](https://github.com/mvdkwast/obsidian-copy-as-html/assets/31014723/257f2a39-4d7e-4bf4-a238-a7cfb2f27885)
*Obsidian Live Preview*
![image|250](https://github.com/mvdkwast/obsidian-copy-as-html/assets/31014723/5897015a-316d-4889-a6f9-c77967d24d1f)
*Google Docs or Gmail*
![image](https://github.com/mvdkwast/obsidian-copy-as-html/assets/31014723/4e0b079e-136f-4080-89fc-219ae4f176c3)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Obsidian 1.3.7 w/ Copy document as HTML v0.5.0

**Additional context**
Thanks for the awesome plugin!  Hard to imagine using Obsidian without it!

**Edit**
Added Obsidian Source Mode Screenshot

**Comment by mvdkwast** [comment]
Hi @senorvalenz, thanks the detailed report ! I can confirm the issue, I will try to look into it, no guarantees about delays unfortunately :)

**Comment by mvdkwast** [comment]
I tried to reproduce this on my dev computer, with an up to date Obsidian (1.4.12), and the image is included correctly, both through a direct link and in a transcluded child document.

If you can still reproduce this, feel free to reopen the issue !

**Comment by senorvalenz** [comment]
Indeed, I just updated to the latest release of your plugin and obsidian, all is well, thanks :)
