### ISSUE TITLE
File name as H1 (FR)

### ISSUE THREAD

**Issue by dushanwegner** [mvdkwast/obsidian-copy-as-html#48]
Hi, as the title says: It would be nice to have an option to copy the filename (page title) as H1 above the content!

**Comment by mvdkwast** [comment]
This is actually a duplicate of !38, and is already available as an option. In the options, activate "Include filename as header" and you should be good.

![image](https://github.com/mvdkwast/obsidian-copy-as-html/assets/2441349/f991b9a6-8c4f-46a4-8920-a5405bf49c7a)
