### ISSUE TITLE
some markdown editor can not recognize image

### ISSUE THREAD

**Issue by eatcosmos** [mvdkwast/obsidian-copy-as-html#51]
# **very helpful for most editor, only not work ok in some kind markdonw editor** https://bytemd.js.org/playground/  https://juejin.cn/editor
![image](https://github.com/mvdkwast/obsidian-copy-as-html/assets/83876321/963c46eb-f38a-485c-b52f-306e580c7b8a)

# **https://bytemd.js.org/playground/**
![image](https://github.com/mvdkwast/obsidian-copy-as-html/assets/83876321/e2997225-8aac-4388-807e-082f90ae74f4)

## but copy image file directly in computer is ok

![image](https://github.com/mvdkwast/obsidian-copy-as-html/assets/83876321/1b1014aa-3773-4eb0-b6c3-cc63db0cfdb6)

**Comment by eatcosmos** [comment]
1. [论坛](#%E8%AE%BA%E5%9D%9B)
1. [需求](#%E9%9C%80%E6%B1%82)
1. [博客](#%E5%8D%9A%E5%AE%A2)

fsadfdffffffffffffffffffffffffffffffffffffffffffffff




fsadfdffffffffffffffffffffffffffffffffffffffffffffff





fsadfdffffffffffffffffffffffffffffffffffffffffffffff




fsadfdffffffffffffffffffffffffffffffffffffffffffffff
# 论坛
- [Obsidian Forum](https://forum.obsidian.md/)

**Comment by mvdkwast** [comment]
Hi @eatcosmos, better late than never as they say. 

Not sure to understand your use-case. From the links that you provided, it seems that you are pasting an obsidian document rendered as HTML into a markdown editor. I don't think that is supposed to work. 

This plugin is rather designed to paste your content into gmail, google docs, or editor widgets like ckedit and the like.

Feel free to reopen this issue if I misunderstood your point !
