### ISSUE TITLE
Plugin fails to remove pinpoints and handle display text of wikilinks

### ISSUE THREAD

**Issue by jonas-sk** [mvdkwast/obsidian-copy-as-html#52]
**Describe the bug**
The plugin fails to remove the `#` and `|` portions of a wikilink if the respective option is activated. In addition, one would expect that the display text would be displayed, rather than the link text. (I suspect it also fails to remove the `^` block pinpoint but simply interprets it as superscript.)

**To Reproduce**
1. Add the following text to an editor: `[[Test link]]. [[Test link header#header]]. [[Test link block#^test]]. [[Test link display test|display text]]`
2. Activate the "Remove Wikilink brackets" option
3. Copy with the assigned hotkey for "copy as html"
4. Paste into e.g. Word

**Result**
`Test link. Test link header#header. Test link block#. Test link display test|display text`

**Expected behavior**
`Test link. Test link header. Test link block. display text`

**Comment by mvdkwast** [comment]
Hi @jonas-sk, sorry for the late answer. 

I think the Obsidian team must have changed how this renders since, because now I get : 

```
Test link.
Test link header > header.
Test link block > ^test.
display text
```

This looks a lot better. Do you feel that it should be an option to remove the `> ...` part also ?

**Comment by fetwar** [comment]
Personally, I think the way it is rendering now is quite nice and more descriptive than just taking the document name itself and throwing away paragraph or block reference info.

I don't have any skin in the matter though so I wouldn't be fussed either way

**Comment by jonas-sk** [comment]
I think the plugin should use the display text when available and, otherwise, the Obsidian rendering of pinpoints and headers works well, as suggested by @mvdkwast. Doing so, it would follow what we see in the Obsidian read mode.

> I think the Obsidian team must have changed how this renders since, because now I get : …

I'm not sure how you get that result, but if I am in edit mode and I invoke the plugin shortcut, the old results still persist.

**Comment by fetwar** [comment]
I agree on that one.

Interesting that we're all getting different results here, I think it may be because of differing Obsidian versions

## Testing
- Using "copy document or selection as HTML" command
- Obsidian version v1.5.12

Markdown for testing
```markdown
[[Test link]].
[[Test link header#header]].
[[Test link block#^test]].
[[Test link display test|display text]]
```

Output in editing mode:
```html
<div><p><span class="internal-link">Test link</span>.<br>
<span class="internal-link">Test link header &gt; header</span>.<br>
<span class="internal-link">Test link block &gt; ^test</span>.<br>
<span class="internal-link">display text</span></p></div>
```

Output in reading mode:
```html
<div><p><span class="internal-link">Test link</span>.<br>
<span class="internal-link">Test link header &gt; header</span>.<br>
<span class="internal-link">Test link block &gt; ^test</span>.<br>
<span class="internal-link">display text</span></p></div>
```

---

Are you running the catalyst 1.6.0+ release of Obsidian @mvdkwast ?

I see that in the [Obsidian Changelog](https://obsidian.md/changelog/) they have made some changes to the link rendering:
> v1.6.0: Added custom instructions and result when adding display text to a link.

**Comment by fetwar** [comment]
I got it to output as described using this markdown:
```markdown
[[Test link broken block link^test]]
```

Which gave this HTML output:
```html
<span class="internal-link">Test link broken block link^test</span><br>
```

but it isn't correctly interpreted by obsidian as a block link anyway, because there is no `#` before the `^`. So I don't believe this needs to work within the plugin.

---

One interesting sidenote is that block definitions aren't included in the HTML output.

e.g.
```markdown
I am the test content ^test
```

```html
<div><p>I am the test content </p></div>
```

**Comment by fetwar** [comment]
I highly doubted it was the command being used, but tried the other two as well.

Copy entire document to clipboard
```html
<div><p><span class="internal-link">Test link</span>.<br>
<span class="internal-link">Test link header &gt; header</span>.<br>
<span class="internal-link">Test link block &gt; ^test</span>.<br>
<span class="internal-link">display text</span><br>
<span class="internal-link">display text for header</span><br>
<span class="internal-link">display text for block</span></p></div>
```

Copy current selection to clipboard
```html
<div><p><span class="internal-link">Test link</span>.<br>
<span class="internal-link">Test link header &gt; header</span>.<br>
<span class="internal-link">Test link block &gt; ^test</span>.<br>
<span class="internal-link">display text</span><br>
<span class="internal-link">display text for header</span><br>
<span class="internal-link">display text for block</span></p></div>
```

**Comment by mvdkwast** [comment]
@jonas-sk, do you still have this problem with the latest version of Obsidian ? If so, feel free to reopen this issue !
