### ISSUE TITLE
mermaid subgraph

### ISSUE THREAD

**Issue by letsgofoiling** [mvdkwast/obsidian-copy-as-html#54]
The following code generates an image with a black background

````
```mermaid
flowchart LR
subgraph title
direction LR
    A(a)-->B(b) 
end
```
```` 

Is the subgraph option supported?
![mermaid-obsidian-subgraph](https://github.com/mvdkwast/obsidian-copy-as-html/assets/161025476/f0bd8b8d-1898-444d-93c3-f453cbd94c2e)

Olivier

**Comment by mvdkwast** [comment]
Hi @letsgofoiling, there seem to be missing css variables for the subgraphs. Will be fixed in the next version. Thank you for reporting !
