### ISSUE TITLE
Plugin has no behavior

### ISSUE THREAD

**Issue by micseydel** [mvdkwast/obsidian-copy-as-html#6]
**Describe the bug**
Right-clicking shows no option to copy as HTML. Using Cmd+P to use the command results in nothing on my clipboard.

**To Reproduce**
1. Attempt to copy
2. Attempt to paste

**Expected behavior**
Pasting would show what was supposedly copied.

**Desktop (please complete the following information):**
 - OS: OS X 12.6
 - Version: Obsidian 1.0

**Comment by mvdkwast** [comment]
Hi @micseydel, thanks for taking the time to leave feedback. 

I haven't been able to test this with OS X unfortunately, so I will to find someone to help me reproducing / analysing this one.

**Comment by mvdkwast** [comment]
Tested on OS X 10.15, couldn't reproduce, so I will need more information :
- are there any error messages in the debug console ?
- did you try multiple documents ? with what kind of content. If you can identify a document that doesn't work, please provide it in source view.
- where did you paste it ?

Thank you

**Comment by mvdkwast** [comment]
Hi @micseydel ,

Would you mind trying the latest version ? I updated the way the copy is triggered, so the command should not appear anymore if you are not in an editor.

The title of the document is not copied, so you need to have something in the document to check it out.

If that doesn't work for you, I'll be glad to accept your offer to test an instrumented version !

**Comment by mvdkwast** [comment]
Something seems wrong : this plugin doesn't require a styles.css file, and the label should say 'Copy document as HTML', not 'Copy as HTML'. There is [another plugin](https://github.com/jenningsb2/copy-as-html) that is called 'Copy as HTML', maybe you're looking at that one ?

Could you try installing it using [BRAT](https://github.com/TfTHacker/obsidian42-brat) in a clean vault ?

**Comment by luckman212** [comment]
Just adding a data point: I tested this plugin (v0.2.3) on macOS 13.0.1 / Obsidian 1.0.3 and it's working fine for me! No errors in the console.

**Comment by micseydel** [comment]
You're right, wrong repo, sorry about that!
